### ISSUE TITLE
Upgrade from 2.2.1 to 2.3.2 breaks

### ISSUE THREAD

**Issue by jacobredesign** [datagrok-ai/tf-module-datagrok-core#52]
Upgrade fails with:
```
Error: associating Route53 Hosted Zone (Z0056175ODXFSBSCTSUZ) to VPC (vpc-0ddaf7613d50e8bdd): PublicZoneVPCAssociation: Attempting to associate public zone: Z0056175ODXFSBSCTSUZ with vpc: vpc-0ddaf7613d50e8bdd status code: 400, request id: b833f642-e25b-42c7-a012-060e36e9e22c
with module.datagrok_dev.module.datagrok_core.aws_route53_zone.internal[0]
on .terraform/modules/datagrok_dev.datagrok_core/aws/lb.tf line 222, in resource "aws_route53_zone" "internal":
resource "aws_route53_zone" "internal" {
```

Happy to reproduce if more information is needed, had to revert it for now in our dev environment.

**Comment by dnillovna** [comment]
@jacobredesign We regret to inform you that after conducting further tests, our teams have determined that there is a limitation on the AWS side. To upgrade from version 2.2.1 to 2.4.0, we recommend manually deleting the old Route53 Hosted Zone (Z0056175ODXFSBSCTSUZ) and creating a new one using terraform. We apologize for any inconvenience this may have caused.
