### ISSUE TITLE
VPC broken on existing deployment

### ISSUE THREAD

**Issue by jacobredesign** [datagrok-ai/tf-module-datagrok-core#53]
Looks like the VPC module used in core is attempting to set
```
enable_classiclink   = null # https://github.com/hashicorp/terraform/issues/31730
```

which is no longer supported by AWS API I believe, resulting in the following error message on plans:

```
Error: Unsupported argument
on .terraform/modules/datagrok.datagrok_core.vpc/main.tf line 1237, in resource "aws_default_vpc" "this":
  enable_classiclink   = null # https://github.com/hashicorp/terraform/issues/31730
An argument named "enable_classiclink" is not expected here.
```

**Comment by dnillovna** [comment]
@jacobredesign We appreciate you bringing the issue to our attention and would like to inform you that an updated version, 2.4.0, will be released on June 20th, which should resolve the problem with the submodule. We apologize for any inconvenience caused and thank you for your patience in this matter.
